# Get token
GET http://localhost:4000/api/v1/captcha/?url=https://glosa.example/best-SO/

# Get token
GET http://localhost:4000/api/v1/captcha/?url=

# Get token
GET http://localhost:4000/api/v1/captcha/

# Get token
GET http://localhost:4000/api/v1/captcha/?other=

# Add comment
POST http://localhost:4000/api/v1/comments/
Content-Type: application/json

{
        "parent": "",
        "token": "VZNQCXMROFBRFSVRTDJN",
        "author": "Cid",
        "email": "campeador@my.email",
        "message": "I like it very much.",
        "thread": "https://glosa.example/best-SO/"
}

# All threads
GET http://localhost:4000/api/v1/threads/search/pyTHon
Content-Type: application/json
Authorization: Bearer mysecret

# Update comment
PUT http://localhost:4000/api/v1/comments/
Content-Type: application/json
Authorization: Bearer mysecret

{
  "id": 4889630303,
  "author": "Julio",
  "email": "my@ide.com",
  "message": "hi my friend"
}

# Delete comment
DELETE http://localhost:4000/api/v1/comments/
Content-Type: application/json
Authorization: Bearer mysecret

{"id": 4889630296}