
# All threads
GET http://localhost:4000/api/v1/threads/
Content-Type: application/json
Authorization: Bearer mysecret

{"search": "PyTHon"}

# Delete comment
DELETE http://localhost:4000/api/v1/comments/4889630295
Authorization: Bearer mysecret
